Repository karnhao/nullshop, pull requests merged in 2022-11, with the labels that each got.

#15 Fluke Add reset password screen
  android/app/src/debug/AndroidManifest.xml
  lib/route.dart
  lib/screens/login_screen.dart
  lib/screens/reset_password_screen.dart
Labels: enhancement

#11 Merge branch karn to master
  assets/placeholderimage.png
  lib/screens/home_screen.dart
  lib/screens/product_info.dart
  lib/services/transaction_service.dart
Labels: documentation, enhancement

#18 Update to master branch. Login with Google | Error handle | Etc...
  android/gradle.properties
  lib/route.dart
  lib/screens/google_account_signin.dart
  lib/screens/home_screen.dart
  lib/screens/login_screen.dart
  lib/screens/product_info.dart
  lib/services/auth_service.dart
  lib/services/database_service_test.dart
  lib/themes/colors.dart
Labels: documentation, enhancement

#20 Buy multiple item fixed!!!!
  lib/screens/product_info.dart
Labels: enhancement

#21 add reload home screen on pull down
  lib/screens/home_screen.dart
Labels: enhancement

#24 Transaction Layout
  lib/screens/add_product_screen.dart
  lib/screens/home_screen.dart
  lib/screens/login_screen.dart
  lib/screens/product_info.dart
  lib/screens/transaction_screen.dart
  pubspec.lock
Labels: enhancement

#26 Fixed infinte loop when data not founded and add app logo
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/logo.png
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  lib/screens/add_product_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#23 Transaction Feature Transaction Service & Transaction Object/Collection
  lib/main.dart
  lib/models/transaction_model.dart
  lib/screens/add_product_screen.dart
  lib/screens/home_screen.dart
  lib/screens/product_info.dart
  lib/screens/profile_screen.dart
  lib/screens/top_up_screen.dart
  lib/screens/transaction_screen.dart
  lib/screens/withdraw_screen.dart
  lib/services/database_service.dart
  lib/services/database_service_interface.dart
  lib/services/transaction_service.dart
  lib/services/transaction_service_interface.dart
  lib/utils/date_time_format.dart
  pubspec.lock
Labels: enhancement
